<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" Version="9.1.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.9" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="NUnit" Version="4.2.2"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.4.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Turso.Raw\Turso.Raw.csproj" />
        <ProjectReference Include="..\Turso.Data\Turso.Data.csproj" />
        <ProjectReference Include="..\Turso.Data.Sqlite\Turso.Data.Sqlite.csproj" />
        <ProjectReference Include="..\Turso.Data.Native\Turso.Data.Native.csproj" />
        <ProjectReference Include="..\Turso.EntityFrameworkCore.Sqlite\Turso.EntityFrameworkCore.Sqlite.csproj" />
        <ProjectReference Include="..\Turso.Core\Turso.Core.csproj" />
        <ProjectReference Include="..\Turso.Platform.Client\Turso.Platform.Client.csproj" />
        <ProjectReference Include="..\Turso.Serverless.Client\Turso.Serverless.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\generate_series.sqltest"
                 Link="Conformance\generate_series.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\limit.sqltest"
                 Link="Conformance\limit.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\simple-count-optimization.sqltest"
                 Link="Conformance\simple-count-optimization.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\concat.sqltest"
                 Link="Conformance\concat.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\delete.sqltest"
                 Link="Conformance\delete.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\update.sqltest"
                 Link="Conformance\update.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\like.sqltest"
                 Link="Conformance\like.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\agg-functions\memory.sqltest"
                 Link="Conformance\agg-functions\memory.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\values.sqltest"
                 Link="Conformance\values.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\cross_join.sqltest"
                 Link="Conformance\cross_join.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\cte.sqltest"
                 Link="Conformance\cte.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\cte-real-affinity-join.sqltest"
                 Link="Conformance\cte-real-affinity-join.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\compound-select-orderby.sqltest"
                 Link="Conformance\compound-select-orderby.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\create_index.sqltest"
                 Link="Conformance\create_index.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\hash-join-three-table-nested.sqltest"
                 Link="Conformance\hash-join-three-table-nested.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\cte_expressions.sqltest"
                 Link="Conformance\cte_expressions.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\cte-union-all-aggregate-literals.sqltest"
                 Link="Conformance\cte-union-all-aggregate-literals.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\union_all.sqltest"
                 Link="Conformance\union_all.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\scalar-functions-datetime.sqltest"
                 Link="Conformance\scalar-functions-datetime.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\scalar-functions.sqltest"
                 Link="Conformance\scalar-functions.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\scalar-functions-format.sqltest"
                 Link="Conformance\scalar-functions-format.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\scalar-functions-printf.sqltest"
                 Link="Conformance\scalar-functions-printf.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\drop_index.sqltest"
                 Link="Conformance\drop_index.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\correlated-subquery-hash-join.sqltest"
                 Link="Conformance\correlated-subquery-hash-join.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\pragma_query_only.sqltest"
                 Link="Conformance\pragma_query_only.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\json\default.sqltest"
                 Link="Conformance\json\default.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\returning.sqltest"
                 Link="Conformance\returning.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\composite-index-sort-elim.sqltest"
                 Link="Conformance\composite-index-sort-elim.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\multi_index_dml.sqltest"
                 Link="Conformance\multi_index_dml.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\window\memory.sqltest"
                 Link="Conformance\window\memory.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\window\filter-over.sqltest"
                 Link="Conformance\window\filter-over.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\managed-recursive-cte-upstream.sqltest"
                 Link="Conformance\managed-recursive-cte-upstream.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\rollback.sqltest"
                 Link="Conformance\rollback.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\default_value.sqltest"
                 Link="Conformance\default_value.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\on_conflict.sqltest"
                 Link="Conformance\on_conflict.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\..\..\sqlite\conformance\sqlite-sqltests\views.sqltest"
                 Link="Conformance\views.sqltest"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
