<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TursoPackageVersion Condition="'$(TursoPackageVersion)' == ''">$(Version)</TursoPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Turso.Data.Sqlite.Native" Version="$(TursoPackageVersion)" />
    <PackageReference Include="Turso.Data.Sqlite.Sync" Version="$(TursoPackageVersion)" />
  </ItemGroup>
</Project>
